services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $defaultOutputDir: '%wexample_symfony_pseudocode.output_dir%'
            $additionalSources: '%wexample_symfony_pseudocode.additional_sources%'

    Wexample\SymfonyPseudocode\:
        resource: '../../{Command,Service}'
        tags: ['controller.service_arguments']
